// <auto-generated />
using System;
using LearnMalti.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnMalti.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114102726_AddImageToLearningItem")]
    partial class AddImageToLearningItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnMalti.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<int>("AssessmentType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssessmentId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("LearnMalti.Models.AssessmentResult", b =>
                {
                    b.Property<int>("AssessmentResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentResultId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreGrammar")
                        .HasColumnType("int");

                    b.Property<int>("ScoreVocabulary")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("AssessmentResultId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("PlayerId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("LearnMalti.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            BadgeId = 1,
                            Description = "Completed the Tutorial",
                            IconKey = "🏅",
                            Name = "Tutorial Master"
                        },
                        new
                        {
                            BadgeId = 2,
                            Description = "Scored 100% on any level",
                            IconKey = "🌟",
                            Name = "Perfect Score"
                        },
                        new
                        {
                            BadgeId = 3,
                            Description = "Finished a level before time ran out",
                            IconKey = "⚡",
                            Name = "Speed Runner"
                        });
                });

            modelBuilder.Entity("LearnMalti.Models.LearningItem", b =>
                {
                    b.Property<int>("LearningItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalteseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LearningItemId");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("LearnMalti.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalXpEarned")
                        .HasColumnType("int");

                    b.Property<int>("YearGroup")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerCode")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LearnMalti.Models.PlayerBadge", b =>
                {
                    b.Property<int>("PlayerBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerBadgeId"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("PlayerBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("PlayerId", "BadgeId")
                        .IsUnique();

                    b.ToTable("PlayerBadges");
                });

            modelBuilder.Entity("LearnMalti.Models.PlayerProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAttemptTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LearningItemId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("WasLastAnswerCorrect")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.HasIndex("PlayerId", "LearningItemId")
                        .IsUnique();

                    b.ToTable("PlayerProgress");
                });

            modelBuilder.Entity("LearnMalti.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("SurveyQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyQuestionId"));

                    b.Property<int?>("TargetMode")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyQuestionId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("LearnMalti.Models.SurveyResponse", b =>
                {
                    b.Property<int>("SurveyResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyResponseId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.HasKey("SurveyResponseId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("LearnMalti.Models.AssessmentResult", b =>
                {
                    b.HasOne("LearnMalti.Models.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMalti.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LearnMalti.Models.PlayerBadge", b =>
                {
                    b.HasOne("LearnMalti.Models.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMalti.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LearnMalti.Models.PlayerProgress", b =>
                {
                    b.HasOne("LearnMalti.Models.LearningItem", "LearningItem")
                        .WithMany()
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMalti.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LearnMalti.Models.SurveyResponse", b =>
                {
                    b.HasOne("LearnMalti.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnMalti.Models.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SurveyQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
